Update flutter to 3.24.5 and set java version to 17
deviniti-apps/devinit pull request #15
Opened 2024-12-31 08:43 UTC by marekbojecdeviniti

2024-12-31 09:50 UTC, wojciechzahradnikdeviniti requested changes

2024-12-31 09:50 UTC, wojciechzahradnikdeviniti commented on templates/template_bitrise.yml
> +            - version: 3.24.5
please also change
```
meta:
  bitrise.io:
    stack: osx-xcode-14.2.x-ventura
```
```
meta:
  bitrise.io:
    stack: osx-xcode-16.2.x-edge
    machine_type_id: g2-m1.4core
```
at the end

2024-12-31 09:50 UTC, wojciechzahradnikdeviniti commented on templates/template_build.gradle
> +    compileSdkVersion 34
it should be `compileSdk` instead of `compileSdkVersion`

2024-12-31 09:50 UTC, wojciechzahradnikdeviniti commented on templates/template_build.gradle
>          minSdkVersion 23
23 -> 26

2024-12-31 09:50 UTC, wojciechzahradnikdeviniti commented on templates/template_root_build.gradle
> +    ext.kotlin_version = '1.9.0'
1.9.20

2024-12-31 09:50 UTC, wojciechzahradnikdeviniti commented on templates/template_README.md
Android ([since API 23] -> Android ([since API 26]

2024-12-31 09:50 UTC, wojciechzahradnikdeviniti commented on templates/template_root_build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
dont you need 
```
classpath 'com.android.tools.build:gradle:8.1.3'
classpath 'com.google.gms:google-services:4.3.8'
```
 also?

2024-12-31 09:50 UTC, wojciechzahradnikdeviniti commented on templates/template_root_build.gradle
don't you need to add this template to create.sh?

2024-12-31 10:14 UTC, marekbojecdeviniti commented on templates/template_root_build.gradle
it's added here:
    echo 'Replacing root build.gradle with template_root_build.gradle'
    cp templates/template_root_build.gradle "$appName"/"$appName"/android/build.gradle

2024-12-31 10:15 UTC, marekbojecdeviniti commented on templates/template_root_build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
no but I will add this either way

2025-01-02 10:55 UTC, wojciechzahradnikdeviniti commented on create.sh
> +    echo 'Replacing root build.gradle with template_root_build.gradle'
can be removed

2025-01-02 10:58 UTC, wojciechzahradnikdeviniti commented on create.sh
> +
does it work properly?

2025-01-02 10:58 UTC, wojciechzahradnikdeviniti approved these changes

2025-01-02 11:42 UTC, marekbojecdeviniti commented on create.sh
> +
yes

2025-01-02 11:46 UTC, wojciechzahradnikdeviniti approved these changes

2025-01-02 11:50 UTC, kamilzajacdeviniti approved these changes

2025-01-02 11:50 UTC, merged